/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientDashboardRouteImport } from './routes/patient-dashboard'
import { Route as MyMedsRouteImport } from './routes/my-meds'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkRouteImport } from './routes/link'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPushVapidRouteImport } from './routes/api.push.vapid'
import { Route as ApiPushOnVitalRouteImport } from './routes/api.push.on-vital'
import { Route as ApiPushOnConfirmRouteImport } from './routes/api.push.on-confirm'
import { Route as ApiPublicHooksCheckMissedMedsRouteImport } from './routes/api.public.hooks.check-missed-meds'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient-dashboard',
  path: '/patient-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMedsRoute = MyMedsRouteImport.update({
  id: '/my-meds',
  path: '/my-meds',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidRoute = ApiPushVapidRouteImport.update({
  id: '/api/push/vapid',
  path: '/api/push/vapid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushOnVitalRoute = ApiPushOnVitalRouteImport.update({
  id: '/api/push/on-vital',
  path: '/api/push/on-vital',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushOnConfirmRoute = ApiPushOnConfirmRouteImport.update({
  id: '/api/push/on-confirm',
  path: '/api/push/on-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckMissedMedsRoute =
  ApiPublicHooksCheckMissedMedsRouteImport.update({
    id: '/api/public/hooks/check-missed-meds',
    path: '/api/public/hooks/check-missed-meds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendar': typeof CalendarRoute
  '/clinics': typeof ClinicsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/my-meds': typeof MyMedsRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/settings': typeof SettingsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/push/on-confirm': typeof ApiPushOnConfirmRoute
  '/api/push/on-vital': typeof ApiPushOnVitalRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/public/hooks/check-missed-meds': typeof ApiPublicHooksCheckMissedMedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendar': typeof CalendarRoute
  '/clinics': typeof ClinicsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/my-meds': typeof MyMedsRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/settings': typeof SettingsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/push/on-confirm': typeof ApiPushOnConfirmRoute
  '/api/push/on-vital': typeof ApiPushOnVitalRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/public/hooks/check-missed-meds': typeof ApiPublicHooksCheckMissedMedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/calendar': typeof CalendarRoute
  '/clinics': typeof ClinicsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/my-meds': typeof MyMedsRoute
  '/patient-dashboard': typeof PatientDashboardRoute
  '/settings': typeof SettingsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/push/on-confirm': typeof ApiPushOnConfirmRoute
  '/api/push/on-vital': typeof ApiPushOnVitalRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/public/hooks/check-missed-meds': typeof ApiPublicHooksCheckMissedMedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/calendar'
    | '/clinics'
    | '/dashboard'
    | '/history'
    | '/link'
    | '/login'
    | '/medications'
    | '/my-meds'
    | '/patient-dashboard'
    | '/settings'
    | '/update-password'
    | '/api/push/on-confirm'
    | '/api/push/on-vital'
    | '/api/push/vapid'
    | '/api/public/hooks/check-missed-meds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/calendar'
    | '/clinics'
    | '/dashboard'
    | '/history'
    | '/link'
    | '/login'
    | '/medications'
    | '/my-meds'
    | '/patient-dashboard'
    | '/settings'
    | '/update-password'
    | '/api/push/on-confirm'
    | '/api/push/on-vital'
    | '/api/push/vapid'
    | '/api/public/hooks/check-missed-meds'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/calendar'
    | '/clinics'
    | '/dashboard'
    | '/history'
    | '/link'
    | '/login'
    | '/medications'
    | '/my-meds'
    | '/patient-dashboard'
    | '/settings'
    | '/update-password'
    | '/api/push/on-confirm'
    | '/api/push/on-vital'
    | '/api/push/vapid'
    | '/api/public/hooks/check-missed-meds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CalendarRoute: typeof CalendarRoute
  ClinicsRoute: typeof ClinicsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LinkRoute: typeof LinkRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  MyMedsRoute: typeof MyMedsRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  SettingsRoute: typeof SettingsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ApiPushOnConfirmRoute: typeof ApiPushOnConfirmRoute
  ApiPushOnVitalRoute: typeof ApiPushOnVitalRoute
  ApiPushVapidRoute: typeof ApiPushVapidRoute
  ApiPublicHooksCheckMissedMedsRoute: typeof ApiPublicHooksCheckMissedMedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-dashboard': {
      id: '/patient-dashboard'
      path: '/patient-dashboard'
      fullPath: '/patient-dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-meds': {
      id: '/my-meds'
      path: '/my-meds'
      fullPath: '/my-meds'
      preLoaderRoute: typeof MyMedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid': {
      id: '/api/push/vapid'
      path: '/api/push/vapid'
      fullPath: '/api/push/vapid'
      preLoaderRoute: typeof ApiPushVapidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/on-vital': {
      id: '/api/push/on-vital'
      path: '/api/push/on-vital'
      fullPath: '/api/push/on-vital'
      preLoaderRoute: typeof ApiPushOnVitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/on-confirm': {
      id: '/api/push/on-confirm'
      path: '/api/push/on-confirm'
      fullPath: '/api/push/on-confirm'
      preLoaderRoute: typeof ApiPushOnConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-missed-meds': {
      id: '/api/public/hooks/check-missed-meds'
      path: '/api/public/hooks/check-missed-meds'
      fullPath: '/api/public/hooks/check-missed-meds'
      preLoaderRoute: typeof ApiPublicHooksCheckMissedMedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CalendarRoute: CalendarRoute,
  ClinicsRoute: ClinicsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LinkRoute: LinkRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  MyMedsRoute: MyMedsRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  SettingsRoute: SettingsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiPushOnConfirmRoute: ApiPushOnConfirmRoute,
  ApiPushOnVitalRoute: ApiPushOnVitalRoute,
  ApiPushVapidRoute: ApiPushVapidRoute,
  ApiPublicHooksCheckMissedMedsRoute: ApiPublicHooksCheckMissedMedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
